language: go
go:
  - tip

install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get gopkg.in/alecthomas/kingpin.v2

script:
  - ./run_tests.sh

branches:
  except:
  - /^wip.*$/